### ISSUE TITLE
Adding entry and exit functions to all states

### ISSUE THREAD

**Issue by distantforest1** [simplystated/f-of-xstate#5]
Hello, I was just recently recommended to try this and I'm happy with the results so far. I have a question though, I'm trying to add an entry action and exit action to every state like the following:

```typescript
const opts = { actions: { Enter: ..., Exit: ... } }

const config = mapStates(machine2, (state) => ({
  ...state,
  meta: {
    newID: state.id
  },
  entry: 'Enter', // <-- Errors here
  exit: 'Exit'    // <-- Errors here
}))
```

However I get this error:

```
Type 'string' is not assignable to type 'ActionObject<unknown, AnyEventObject>[]'.ts(2322)
types.d.ts(447, 5): The expected type comes from property 'entry' which is declared here on type 'StructuredTransformedStateNodeConfig<unknown, any, AnyEventObject>'
```

How would I get the entry and exit functions to work on all of my states?

**Comment by distantforest1** [comment]
Managed to figure it out. Using `actions.toActionObject()` seems to work.

```typescript
import { actions } from 'xstate';
import { mapStates } from "@simplystated/f-of-xstate";

{
  ...
  entry: [actions.toActionObject((...params) => { console.log(["entry ", state.id]) })],
  exit: [actions.toActionObject((...params) => { console.log(["exit ", state.id]) })],
  ...
}
```

Thanks!

**Comment by abrgr** [comment]
Very happy that f-of-xstate has been useful to you.

You can use `toActionObject`, as you found, or directly return an object with a string `type` and an optional `exec` function (and optional `meta`). You don't need the `exec` function if you plan to supply it via machine options when you call `createMachine`.

Please let me know any other issues or anything we can help with.

**Comment by distantforest1** [comment]
Thanks!
